before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
    - CGO_ENABLED=0
    binary: check-xid-age
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
artifactories:
  - name: opentable
    mode: archive
    target: http://artifactory.otenv.com/artifactory/ot-golang/{{ .ProjectName }}/{{ .Version }}/
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
